module.exports = {
    "labels": {
        "JavaScript": [ "JavaScript", "ES ?6", "ES ?2015"],
        "ES2015": ["ES ?6", "ES ?2015", "ecmascript", "babel", "(箭头函数|Promise|generator|async|await)"],
        "HTTP": [ "http[^:]", "OCSP", "HPKP", "SSL", "HSTS", "CSP", "请求头", "响应头"],
        "HTML5": [ "HTML ?5", "h5"],
        "CSS": ["css3?", "flex ?box", "(圆角|阴影|渐变)"],
        "函数式编程": ["函数式", "FP\W"],
        "Node.js": ["Nodejs", "npm", "Node\W"],
        "Vue.js": ["Vue\.?js"],
        "Angular": ["angular"],
        "React": ["React\W", "React ?Native", "Flux"],
        "Webpack": ["webpack"],
        "Gulp": ["gulp"],
        "Grunt": ["grunt"],
        "Babel": ["Babel"],
        "前端工程": ["(工程|编译|部署|上线|代码压缩|文件合并|模块|组件|单元测试)", "(gulp|grunt|rollup|webpack|babel)"],
        "SVG": ["SVG"],
        "性能": ["(性能|优化|缓存|渲染|加载速度|卡顿|阻塞|流畅)"],
        "框架": ["框架", "(jQuery|Angular|Vue)"],
        "Web 安全": ["安全", "漏洞", "(XSS|CSRF)"],
        "教程": ["教程", "入门"],
        "移动 Web": ["移动", "Android", "iOS", "手机", "touch", "viewport"],
        "git": ["git"],
        "职业": ["职业", "工程师"],
        "动画": ["动画", "(animation|keyframes|transition)"],
        "测试": ["(单元|代码)测试", "(Karma|mocha|sinon)"],
        "工具": ["工具"],
        "服务端": ["(PHP|nginx|apache)"]
    }
};
